//! Minimal tpt-archon app: open a file-backed database, INSERT a row, SELECT it.
//!
//! Generated by `cargo generate` from the `template/` directory of the
//! tpt-archon repo. See `docs/GETTING_STARTED.md` for the full walkthrough.

use tpt_archon_core::storage::Database;
use tpt_archon_relational::database::{ColumnType, Database as RelDb, Schema};
use tpt_archon_relational::parser::parse_statement;

fn main() {
    // --- 1. Embeddable core: file-backed storage engine (WAL + buffer pool) ---
    let path = "app.db.bin";
    let _ = std::fs::remove_file(path);
    {
        let mut db = Database::create(path, 64).expect("create db");
        let page = vec![0u8; tpt_archon_core::page::PAGE_SIZE];
        db.put(0, &page).expect("write page");
    }

    // --- 2. Relational layer: store rows in the core B-Link tree ---
    let schema = Schema {
        columns: vec!["id".into(), "name".into(), "age".into()],
        types: vec![ColumnType::Int, ColumnType::Text, ColumnType::Int],
    };
    let mut rdb = RelDb::new(schema);

    rdb.execute(
        &parse_statement("INSERT INTO t (id, name, age) VALUES (1, 'alice', 30)").unwrap(),
        &[],
    )
    .expect("insert");

    let result = rdb
        .execute(&parse_statement("SELECT id, name FROM t WHERE age >= 30").unwrap(), &[])
        .expect("select");

    println!("columns: {:?}", result.columns);
    for row in &result.rows {
        println!("  row: {row:?}");
    }
    assert_eq!(result.rows.len(), 1);

    let _ = std::fs::remove_file(path);
    println!("{}: INSERT + SELECT OK", "{{project-name}}");
}
