//! Code generation: lower the erased eidos computational core to `no_std` Rust.
//!
//! The output is a complete, self-contained `#![no_std]` crate that depends on
//! nothing but `core`. All proof machinery (refinements, contracts, the kernel,
//! the QF_LRA verifier) has been erased, so no verification artifact leaks into
//! the generated source and there is zero runtime cost from verification.
//!
//! Array helpers (`eidos_map`, `eidos_zip`, `eidos_magnitude`, `eidos_len`) are
//! emitted as `const`-generic, stack-only functions, so generated code never
//! allocates.

use tpt_eidos_erasure::{CExpr, CExprKind, CoreFun, CoreModule, CoreType, StructDef};
use tpt_eidos_parser::Pattern;

/// Lower an erased core module to a `no_std` Rust source string.
///
/// Returns `Err` when the core cannot be lowered to valid Rust (e.g. a `.map`
/// or `.zip` without its required closure/argument). Reporting the failure
/// instead of panicking or emitting silently-invalid Rust is what keeps
/// `eidos build` honest (bug #10).
pub fn codegen(module: &CoreModule) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("#![no_std]\n");
    out.push_str("// Generated by tpt-eidos (erasure + codegen). Do not edit by hand.\n");
    out.push_str("// This module was verified by the eidos kernel; all proof terms\n");
    out.push_str("// have been erased. It depends only on `core`.\n\n");

    out.push_str(&prelude());
    out.push('\n');

    for s in &module.structs {
        out.push_str(&gen_struct(s));
        out.push('\n');
    }
    if !module.structs.is_empty() {
        out.push('\n');
    }

    for f in &module.fns {
        out.push_str(&gen_fun(f)?);
        out.push('\n');
    }

    Ok(out)
}

fn prelude() -> String {
    "\
#[inline]
pub fn eidos_len<const N: usize>(_a: [f64; N]) -> usize {
    N
}

#[inline]
pub fn eidos_sqrt(x: f64) -> f64 {
    if x <= 0.0 {
        return 0.0;
    }
    // Scale `x` into [1, 4) so that 32 Newton iterations converge to full f64
    // precision even for extreme magnitudes (bug #11). The final result is
    // rescaled back; this keeps the verified (exact-real) contract and the
    // generated (float) computation consistent across the dynamic range.
    let mut y = x;
    let mut scale = 1.0f64;
    while y >= 4.0 {
        y *= 0.25;
        scale *= 2.0;
    }
    while y < 1.0 {
        y *= 4.0;
        scale *= 0.5;
    }
    let mut g = y;
    let mut i = 0usize;
    while i < 32 {
        g = 0.5 * (g + y / g);
        i += 1;
    }
    g * scale
}

#[inline]
pub fn eidos_magnitude<const N: usize>(a: [f64; N]) -> f64 {
    let mut s = 0.0f64;
    let mut i = 0usize;
    while i < N {
        s = s + a[i] * a[i];
        i += 1;
    }
    eidos_sqrt(s)
}

#[inline]
pub fn eidos_map<const N: usize, T, R, F>(a: [T; N], f: F) -> [R; N]
where
    T: Copy,
    F: Fn(T) -> R,
{
    core::array::from_fn(|i| f(a[i]))
}

#[inline]
pub fn eidos_zip<const N: usize>(a: [f64; N], b: [f64; N]) -> [(f64, f64); N] {
    core::array::from_fn(|i| (a[i], b[i]))
}
"
    .to_string()
}

fn gen_struct(s: &StructDef) -> String {
    let fields = s
        .fields
        .iter()
        .map(|(n, t)| format!("    pub {}: {},", ident(n), gen_type(t)))
        .collect::<Vec<_>>()
        .join("\n");
    format!("pub struct {} {{\n{}\n}}\n", ident(&s.name), fields)
}

fn gen_fun(f: &CoreFun) -> Result<String, String> {
    let params = f
        .params
        .iter()
        .map(|(n, t)| format!("{}: {}", ident(n), gen_type(t)))
        .collect::<Vec<_>>()
        .join(", ");
    let ret = gen_type(&f.ret);
    let body = gen_block(&f.body, 1)?;
    Ok(format!(
        "pub fn {} ({}) -> {} {{\n{}}}\n",
        ident(&f.name),
        params,
        ret,
        body
    ))
}

fn gen_type(t: &CoreType) -> String {
    match t {
        CoreType::Base(s) => base_type(s),
        CoreType::Array(inner, n) => format!("[{}; {}]", gen_type(inner), n),
        CoreType::Named(n) => n.clone(),
    }
}

fn base_type(s: &str) -> String {
    match s {
        "Unit" => "()".to_string(),
        other => other.to_string(),
    }
}

/// Render an expression in *value* position (no trailing semicolon).
fn gen_expr(e: &CExpr) -> Result<String, String> {
    match &e.kind {
        CExprKind::Num(n) => Ok(float_lit(*n)),
        CExprKind::Bool(b) => Ok(b.to_string()),
        CExprKind::Var(v) => Ok(ident(v)),
        CExprKind::ArrayLit(es) => {
            let mut elems = Vec::new();
            for x in es {
                elems.push(gen_expr(x)?);
            }
            Ok(format!("[{}]", elems.join(", ")))
        }
        CExprKind::Bin { op, a, b } => Ok(format!(
            "({} {} {})",
            gen_expr(a)?,
            binop_str(*op),
            gen_expr(b)?
        )),
        CExprKind::Un { op, a } => match op {
            tpt_eidos_parser::UnOp::Neg => Ok(format!("(-{})", gen_expr(a)?)),
            tpt_eidos_parser::UnOp::Not => Ok(format!("(!{})", gen_expr(a)?)),
        },
        CExprKind::If { cond, then, els } => Ok(format!(
            "if {} {{ {} }} else {{ {} }}",
            gen_expr(cond)?,
            gen_block(then, 0)?,
            gen_block(els, 0)?
        )),
        CExprKind::Let { name, value, body } => Ok(format!(
            "{{ let {} = {}; {} }}",
            ident(name),
            gen_expr(value)?,
            gen_block(body, 0)?
        )),
        CExprKind::Call { func, args } => {
            let mut a = Vec::new();
            for x in args {
                a.push(gen_expr(x)?);
            }
            Ok(format!("{}({})", ident(func), a.join(", ")))
        }
        CExprKind::Method { recv, name, args } => gen_method(recv, name, args),
        CExprKind::Lambda { params, body } => {
            let ps = gen_pattern_list(params);
            Ok(format!("|{ps}| {}", gen_expr(body)?))
        }
        CExprKind::Record(fields) => gen_record(e, fields),
        CExprKind::Return(inner) => Ok(format!("return {}", gen_expr(inner)?)),
    }
}

/// Render an expression in *statement / tail* position, adding a semicolon to
/// `return` so it terminates the enclosing block.
fn gen_block(e: &CExpr, _indent: usize) -> Result<String, String> {
    match &e.kind {
        CExprKind::Return(inner) => Ok(format!("return {};", gen_expr(inner)?)),
        CExprKind::If { cond, then, els } => Ok(format!(
            "if {} {{\n{}    }} else {{\n{}    }}",
            gen_expr(cond)?,
            indent_block(&gen_block(then, 0)?),
            indent_block(&gen_block(els, 0)?)
        )),
        CExprKind::Let { name, value, body } => Ok(format!(
            "let {} = {};\n{}",
            ident(name),
            gen_expr(value)?,
            gen_block(body, 0)?
        )),
        other => {
            let _ = other;
            gen_expr(e)
        }
    }
}

/// Indent every line of `s` by four spaces and ensure it ends with a newline.
fn indent_block(s: &str) -> String {
    let mut out = String::new();
    for line in s.lines() {
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn gen_method(recv: &CExpr, name: &str, args: &[CExpr]) -> Result<String, String> {
    let r = gen_expr(recv)?;
    match name {
        "magnitude" => Ok(format!("eidos_magnitude({})", r)),
        "len" => Ok(format!("eidos_len({})", r)),
        "map" => {
            let lam = args
                .first()
                .ok_or_else(|| "eidos_map requires a closure argument".to_string())?;
            let (params, body) = match &lam.kind {
                CExprKind::Lambda { params, body } => (params.clone(), gen_expr(body)?),
                _ => (Vec::new(), gen_expr(lam)?),
            };
            let param_str = gen_pattern_list(&params);
            Ok(format!("eidos_map({}, |{}| {})", r, param_str, body))
        }
        "zip" => {
            let a = args
                .first()
                .ok_or_else(|| "eidos_zip requires a second array argument".to_string())?;
            Ok(format!("eidos_zip({}, {})", r, gen_expr(a)?))
        }
        _ => {
            if args.is_empty() {
                Ok(format!("{}.{}", r, name))
            } else {
                let mut a = Vec::new();
                for x in args {
                    a.push(gen_expr(x)?);
                }
                Ok(format!("{}.{}({})", r, name, a.join(", ")))
            }
        }
    }
}

fn gen_record(e: &CExpr, fields: &[(String, CExpr)]) -> Result<String, String> {
    let name = match &e.ty {
        CoreType::Named(n) => Some(n.clone()),
        _ => None,
    };
    let mut body = Vec::new();
    for (n, v) in fields {
        body.push(format!("{}: {}", ident(n), gen_expr(v)?));
    }
    let body = body.join(", ");
    match name {
        Some(n) => Ok(format!("{} {{ {} }}", ident(&n), body)),
        None => Err("anonymous records are not supported as a codegen target".to_string()),
    }
}

fn gen_pattern(p: &Pattern) -> String {
    match p {
        Pattern::Var(v) => ident(v),
        Pattern::Tuple(ps) => format!("({})", gen_pattern_list(ps)),
    }
}

fn gen_pattern_list(params: &[Pattern]) -> String {
    params
        .iter()
        .map(gen_pattern)
        .collect::<Vec<_>>()
        .join(", ")
}

fn float_lit(n: f64) -> String {
    if n.is_infinite() {
        return if n > 0.0 {
            "f64::INFINITY".to_string()
        } else {
            "f64::NEG_INFINITY".to_string()
        };
    }
    if n.is_nan() {
        return "f64::NAN".to_string();
    }
    let s = format!("{n}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

/// Render an identifier for emitted Rust, escaping reserved keywords with the
/// raw-identifier `r#` form so field/function names like `loop` or `type`
/// produce compilable Rust (bug #13).
fn ident(s: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn",
    ];
    if KEYWORDS.contains(&s) {
        format!("r#{s}")
    } else {
        s.to_string()
    }
}

fn binop_str(op: tpt_eidos_parser::BinOp) -> &'static str {
    use tpt_eidos_parser::BinOp;
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::Lt => "<",
        BinOp::Gt => ">",
        BinOp::Le => "<=",
        BinOp::Ge => ">=",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    use tpt_eidos_erasure::erase;
    use tpt_eidos_parser::parse;

    fn gen_src(src: &str) -> String {
        let m = parse(src).expect("parse");
        let core = erase(&m);
        codegen(&core).expect("codegen")
    }

    #[test]
    fn emits_no_std_and_helpers() {
        let out = gen_src("fn f(a: f64) -> f64 { return a + 1.0; }");
        assert!(out.contains("#![no_std]"));
        assert!(out.contains("pub fn eidos_map"));
        assert!(out.contains("pub fn eidos_magnitude"));
    }

    #[test]
    fn emits_struct_for_refinement() {
        let out = gen_src(
            "type NV = { v: Array<f64, 1> | v.magnitude() <= 1.0 };
             fn f(x: f64) -> NV { return { v: [x] } as NV; }",
        );
        assert!(out.contains("pub struct NV"));
        assert!(out.contains("pub v: [f64; 1],"));
        assert!(out.contains("NV { v: [x] }"), "got:\n{out}");
    }

    #[test]
    fn emits_map_zip_pipeline() {
        let out = gen_src(
            "fn f(a: Array<f64, 3>, b: Array<f64, 3>) -> Array<f64, 3> {
                return a.zip(b).map(|(x, y)| x - y);
            }",
        );
        assert!(
            out.contains("eidos_map(eidos_zip(a, b), |(x, y)|"),
            "got:\n{out}"
        );
    }

    #[test]
    fn no_kernel_types_leak() {
        let out = gen_src(
            "type NV = { v: Array<f64, 3> | v.magnitude() <= 1.0 };
             fn g(a: Array<f64, 3>) -> NV requires a.magnitude() > 0.0 {
                 if a.magnitude() > 0.0 { return { v: a.map(|x| x) } as NV; }
                 else { return { v: [0.0, 0.0, 0.0] } as NV; }
             }",
        );
        assert!(!out.contains("Refine"));
        assert!(!out.contains("Constraint"));
        assert!(!out.contains("eidos_kernel"));
        assert!(!out.contains("eidos_verifier"));
    }

    // --- Bug #9: refinement bind name other than "v" must still codegen. ---

    #[test]
    fn refinement_bind_other_than_v() {
        let out = gen_src(
            "type NV = { w: Array<f64, 1> | w.magnitude() <= 1.0 };
             fn f(x: f64) -> NV { return { w: [x] } as NV; }",
        );
        assert!(out.contains("pub struct NV"));
        assert!(out.contains("pub w: [f64; 1],"), "got:\n{out}");
        assert!(out.contains("NV { w: [x] }"), "got:\n{out}");
    }

    // --- Bug #10: `.map`/`.zip` without their argument must error, not panic
    // or silently emit invalid Rust. ---

    #[test]
    fn map_without_closure_is_error() {
        let m = parse("fn f(a: Array<f64, 3>) -> Array<f64, 3> { return a.map(); }").unwrap();
        let core = erase(&m);
        assert!(
            codegen(&core).is_err(),
            "map without closure must be rejected"
        );
    }

    #[test]
    fn zip_without_second_arg_is_error() {
        let m = parse("fn f(a: Array<f64, 3>) -> Array<f64, 3> { return a.zip(); }").unwrap();
        let core = erase(&m);
        assert!(
            codegen(&core).is_err(),
            "zip without second arg must be rejected"
        );
    }

    // --- Bug #12: non-finite float literals must produce valid Rust. ---

    #[test]
    fn non_finite_float_literal() {
        assert_eq!(float_lit(f64::INFINITY), "f64::INFINITY");
        assert_eq!(float_lit(f64::NEG_INFINITY), "f64::NEG_INFINITY");
        assert_eq!(float_lit(f64::NAN), "f64::NAN");
    }

    // --- Bug #13: identifiers colliding with Rust keywords must be escaped. ---

    #[test]
    fn keyword_ident_escaped() {
        let out = gen_src(
            "type T = { loop: Array<f64, 1> | loop.magnitude() <= 1.0 };
             fn f(x: f64) -> T { return { loop: [x] } as T; }",
        );
        assert!(
            out.contains("pub struct T {") && out.contains("pub r#loop: [f64; 1],"),
            "got:\n{out}"
        );
        assert!(out.contains("T { r#loop: [x] }"), "got:\n{out}");
        assert!(!out.contains("pub loop:"), "raw keyword must be escaped");
    }

    // --- Bug #11: generated float math must compute the right answer at
    // runtime, including extreme magnitudes. Compiles + runs the generated
    // prelude helpers with `rustc`; skipped if rustc is unavailable. ---

    #[test]
    fn generated_math_executes_correctly() {
        let rustc = match Command::new("rustc").arg("--version").output() {
            Ok(o) if o.status.success() => "rustc",
            _ => {
                eprintln!("skipping generated-math execution test: rustc not found");
                return;
            }
        };
        let src = format!(
            "{}\n\nfn main() {{\n    println!(\"{{}} {{}} {{}} {{}}\", eidos_sqrt(2.0), eidos_sqrt(1e30), eidos_sqrt(1e-30), eidos_magnitude([3.0, 4.0, 0.0]));\n}}\n",
            prelude()
        );
        let dir = std::env::temp_dir().join("eidos_codegen_exec_test");
        std::fs::create_dir_all(&dir).expect("create temp dir");
        let file = dir.join("main.rs");
        std::fs::write(&file, &src).expect("write main.rs");
        let exe = dir.join("main");
        let build = Command::new(rustc)
            .args(["--edition", "2021", "-O"])
            .arg(file.as_os_str())
            .arg("-o")
            .arg(exe.as_os_str())
            .output()
            .expect("run rustc");
        assert!(
            build.status.success(),
            "generated math must compile:\n{}",
            String::from_utf8_lossy(&build.stderr)
        );
        let run = Command::new(&exe).output().expect("run generated binary");
        let out = String::from_utf8_lossy(&run.stdout);
        let nums: Vec<f64> = out
            .split_whitespace()
            .filter_map(|s| s.parse::<f64>().ok())
            .collect();
        assert_eq!(nums.len(), 4, "expected four numbers, got: {out}");
        assert!(
            (nums[0] - 2.0f64.sqrt()).abs() < 1e-9,
            "sqrt(2) wrong: {}",
            nums[0]
        );
        assert!(
            (nums[1] - 1e15).abs() < 1e9,
            "sqrt(1e30) wrong: {}",
            nums[1]
        );
        assert!(
            (nums[2] - 1e-15).abs() < 1e-21,
            "sqrt(1e-30) wrong: {}",
            nums[2]
        );
        assert!(
            (nums[3] - 5.0).abs() < 1e-9,
            "magnitude([3,4,0]) wrong: {}",
            nums[3]
        );
    }
}
